### ISSUE TITLE
Game freezes when closing the game immediately after it starts

### ISSUE THREAD

**Issue by NagaseIori** [godot-extended-libraries/godot-debug-menu#23]
Reproducible with Debug Menu v1.2.0 in Godot v4.2.1.stable.mono.official [b09f793f5].

### System Information
Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.4633) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue Description

Closing the game immediately after it starts causes the game to freeze when the "Debug Menu" addon is enabled.

### Minimal reproduction project (MRP)
[Test_Bug.zip](https://github.com/godot-extended-libraries/godot-debug-menu/files/13787219/Test_Bug.zip)

**Comment by Calinou** [comment]
I can't reproduce this on my end with Godot 4.2.1 and Debug Menu 1.2.0 on Linux. Here it is working after being installed in an empty project:

![image](https://github.com/godot-extended-libraries/godot-debug-menu/assets/180032/214e4b54-cd3b-48c7-bce7-ccd5075db030)

**Comment by NagaseIori** [comment]
> I can't reproduce this on my end with Godot 4.2.1 and Debug Menu 1.2.0 on Linux. Here it is working after being installed in an empty project:
> 
> ![image](https://private-user-images.githubusercontent.com/180032/293601276-214e4b54-cd3b-48c7-bce7-ccd5075db030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTY5NDAsIm5iZiI6MTcwNDE1NjY0MCwicGF0aCI6Ii8xODAwMzIvMjkzNjAxMjc2LTIxNGU0YjU0LWNkM2ItNDhjNy1iY2U3LWNjZDUwNzVkYjAzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwMDUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2M4Njc0ZWQyZTg4YTY3MmQ0NWRjZjJlMmIzZjcxOTg3YTU2ZjZhN2YzZTNiY2NhOWNkNDNlZWQwM2YyYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x0xQJc6jaISRGjs7KnQ7x88OecJNrK8bEVm9--PDtYs)

To reproduce the issue, I need to close the game right after launch, before the debug menu loads hardware and project info. It will then become unresponsive, as shown below:

![](https://github.com/godot-extended-libraries/godot-debug-menu/assets/31349569/a0561d76-bbdf-4d09-a345-8ae48d31537f)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godot-extended-libraries/godot-debug-menu/issues/22.
