### ISSUE TITLE
Module branch

### ISSUE THREAD

**Issue by scriptsengineer** [godot-extended-libraries/godot-debug-menu#25]
A branch would be interesting:
A branch module that would be a mirror of the master, but ready to be added via git modules

I created mine here [https://github.com/expressobits/godot-debug-menu/tree/module](https://github.com/expressobits/godot-debug-menu/tree/module)

**Comment by Calinou** [comment]
This would mean more maintenance (I already need to keep the demo project repository in sync manually), so I'm afraid not.
