### ISSUE TITLE
can I use DebugMenu **INSIDE** the editor?

### ISSUE THREAD

**Issue by jasonswearingen** [godot-extended-libraries/godot-debug-menu#28]
Hello Is there an easy way to use this inside the godot editor?  I'd like to see approximate render details during development.

Thank you

**Comment by Calinou** [comment]
You can use the existing **View Information** and **View Frame Time** panels in the 3D editor viewport's **Perspective** menu, but this add-on is not designed to work within the editor. There are no plans to modify it for doing so, as this would need a complete refactor and a different UI.

**Comment by jasonswearingen** [comment]
thank you, the " View Frame Time" option is what I needed.
