### ISSUE TITLE
FPS doesnt update properly when scenetree is paused, thefore artificialy lowering the displayed fps

### ISSUE THREAD

**Issue by emanvidmaker** [godot-extended-libraries/godot-debug-menu#29]
**Issue**:
When scenetree is paused, the FPS counter becomes unreliable and displays lower numbers, than real fps.
since its just not updating the delta time beacuse the process is paused. Caused by the root canvas layer being in inherit process mode, thefore artificially lowering the fps.
**Fix**:
Set the root canvas layer to process allways.

* Found it when bugging my game for why there was ""low"" fps when paused on a near empty room; it was the counter

**Comment by Calinou** [comment]
Fixed in:

- https://github.com/godot-extended-libraries/godot-debug-menu/commit/0474847f9cca416a339a1d6aae4791d7fba26204
- https://github.com/godot-extended-libraries/godot-debug-menu-demo/commit/402e4306f09c2e4cab879b1fc20d6b4b7f4026a4
