### ISSUE TITLE
debug menu showing twice

### ISSUE THREAD

**Issue by leleleSDX** [godot-extended-libraries/godot-debug-menu#3]
![godot_debug_edit](https://github.com/godot-extended-libraries/godot-debug-menu/assets/6260996/31ac0a42-ab6a-4e00-8d42-6429a0d685b8)
![godot_debug_menu](https://github.com/godot-extended-libraries/godot-debug-menu/assets/6260996/8ffd96ca-3192-4f3c-8b22-0894923adff2)

it isn't obvious at first. but if you attach the debug menu to a control node, move it at a different position other than top left, then it shows up twice. the new position and always at the top left position.

**Comment by Calinou** [comment]
The debug menu scene is already registered as a singleton. You should not instance it manually in a scene.

**Comment by leleleSDX** [comment]
is there a way to not autoload it? so i can manually set its position in the editor canvas?

**Comment by Calinou** [comment]
> is there a way to not autoload it? so i can manually set its position in the editor canvas?

There isn't a way to customize the position yet (without editing the scene file), but I could add project settings for that.
