### ISSUE TITLE
README.md shows incorrect enum

### ISSUE THREAD

**Issue by ZenithStar** [godot-extended-libraries/godot-debug-menu#32]
https://github.com/godot-extended-libraries/godot-debug-menu/blob/3211673efc9d1e41f94bbd74705eaed2d2b8bdd7/README.md?plain=1#L142

DebugMenu.Style.NONE -> DebugMenu.Style.HIDDEN

**Comment by Calinou** [comment]
Fixed by:

- https://github.com/godot-extended-libraries/godot-debug-menu/commit/0e5f15217285c76170039c9cefcf79c8ab0ec6b3
- https://github.com/godot-extended-libraries/godot-debug-menu-demo/commit/5b256e0bc45d4de41ad91d6cb6ca74a988b11a3c
