### ISSUE TITLE
The most minor problem ever: F3 to "pop up"

### ISSUE THREAD

**Issue by Dangomation** [godot-extended-libraries/godot-debug-menu#5]
Not a big issue of course just a bit annoying that's all:

Having the key detection exclusively when the key is reported is annoying when you can "flicker" the Debug Menu Performance screen by holding the key.

![image](https://github.com/godot-extended-libraries/godot-debug-menu/assets/100386195/41d5714e-e3b3-47d0-8e76-cce4693026b0)

What I replaced it with is of course a super simple solution I've done up myself. 
Change to some sort of "just pressed" please. Thanks!

**Comment by Calinou** [comment]
`if event.is_action_pressed` should already take care of ignoring echo events (key repeat).
