### ISSUE TITLE
DebugMenu ends up getting created behind the scene

### ISSUE THREAD

**Issue by chaeyan** [godot-extended-libraries/godot-debug-menu#6]
As title says, the DebugMenu node gets added behind the current scene when it needs to be above.
<img width="269" alt="Ekran Resmi 2023-06-07 16 45 17" src="https://github.com/godot-extended-libraries/godot-debug-menu/assets/32681723/71a0d687-f7f7-4c9a-be85-6238773933f9">

**Comment by chaeyan** [comment]
Setting `z_index` to max value in `_ready()` solves this issue.

<img width="234" alt="Ekran Resmi 2023-06-07 16 47 28" src="https://github.com/godot-extended-libraries/godot-debug-menu/assets/32681723/a3255ead-f9ef-47f4-88f1-bb5bffed8063">

**Comment by chaeyan** [comment]
Fixed in #7

**Comment by Calinou** [comment]
Reopening, as the associated PR hasn't been merged yet.

**Comment by Calinou** [comment]
Fixed by https://github.com/godot-extended-libraries/godot-debug-menu/commit/2d1bf27e5901186080e0fde5adc56df65dd9c583, which also fixes the issue with Camera2D nodes making the debug menu appear offset. The demo project has been modified to demonstrate this use case.
